### ISSUE TITLE
IPC 

### ISSUE THREAD

**Issue by gedw99** [aperturerobotics/controllerbus#1]
I assume it’s only designed for Linux ? 

Would be cool to be able to use pic on desktop but I assume that needs native golang code with build tags .

what environment are you designing for 

really interesting project btw !!

**Comment by paralin** [comment]
Hi @gedw99 and welcome

I'm currently finishing off the following features which will be propagated to ControllerBus soon (tm):

 - BroadcastChannel (in web browser) and WebWorkers
 - Sub-process (linux sub-process) - named pipes and/or stdin/stdout
 - Networked (k8s pod)
 - Wasm sub-process (via wasmer-go)

Developers will be able to declare a topology of configs to run on available Bus. The Bus are bridged using "bridge controllers" which forward directives conditionally up/down the Bus tree.

**Comment by gedw99** [comment]
Hey @paralin 

sorry about late reply. 

The wasm stuff for browser and server sounds very useful for me . 

I probably got the wrong end of the stick when I started asking about IPC. To make this easier let me reframe my question …

does the server part ( sub processes is what you called it above ) support Windows and MAC ?

the reason I ask is because I am working on a system that runs on desktops where the system is modular in that just like the Service Factory pattern ( Thankyou Martin Fowker we worship you :) ) the implementation can be swapped out at runtime. 

I am getting the feeling that wasm is your engine to allow swapping out on the server / desktop . Like a poor man’s docker . 

Sorry about all the vague questions but this system is pretty unique and so searching for it’s use case fit a bit .

**Comment by paralin** [comment]
@gedw99 Check out Bifrost, which uses controller-bus: https://github.com/aperturerobotics/bifrost

**Comment by paralin** [comment]
More IPC info coming soon. closing this issue for now
