### ISSUE TITLE
Plugins as wasm

### ISSUE THREAD

**Issue by gedw99** [aperturerobotics/controllerbus#5]
Windows does not support shared object builds, but Wazero can run the plugins as wasm. It’s just an idea .

**Comment by paralin** [comment]
I've built something for this & plan to release it sometime this year.

**Comment by gedw99** [comment]
Thanks @paralin 

great project btw

**Comment by paralin** [comment]
ControllerBus supports wasm 100% and I have a separate project for the wasm-as-plugins. Will release it sometime soon!
